/// 泰国行政区划之县
const Map<String, dynamic> thaCitiesData = <String, dynamic>{
  'TH10': <String, Map<String, String>>{
    'TH1050': <String, String>{'name': 'บางบอน', 'alpha': 'บ'},
    'TH1006': <String, String>{'name': 'บางกะปิ', 'alpha': 'บ'},
    'TH1040': <String, String>{'name': 'บางแค', 'alpha': 'บ'},
    'TH1005': <String, String>{'name': 'บางเขน', 'alpha': 'บ'},
    'TH1031': <String, String>{'name': 'บางคอแหลม', 'alpha': 'บ'},
    'TH1021': <String, String>{'name': 'บางขุนเทียน', 'alpha': 'บ'},
    'TH1047': <String, String>{'name': 'บางนา', 'alpha': 'บ'},
    'TH1025': <String, String>{'name': 'บางพลัด', 'alpha': 'บ'},
    'TH1004': <String, String>{'name': 'บางรัก', 'alpha': 'บ'},
    'TH1029': <String, String>{'name': 'บางซื่อ', 'alpha': 'บ'},
    'TH1020': <String, String>{'name': 'บางกอกน้อย', 'alpha': 'บ'},
    'TH1016': <String, String>{'name': 'บางกอกใหญ่', 'alpha': 'บ'},
    'TH1027': <String, String>{'name': 'บึงกุ่ม', 'alpha': 'บึ'},
    'TH1030': <String, String>{'name': 'จตุจักร', 'alpha': 'จ'},
    'TH1035': <String, String>{'name': 'จอมทอง', 'alpha': 'จ'},
    'TH1026': <String, String>{'name': 'ดินแดง', 'alpha': 'ดิ'},
    'TH1036': <String, String>{'name': 'ดอนเมือง', 'alpha': 'ด'},
    'TH1002': <String, String>{'name': 'ดุสิต', 'alpha': 'ดุ'},
    'TH1017': <String, String>{'name': 'ห้วยขวาง', 'alpha': 'ห้'},
    'TH1043': <String, String>{'name': 'คันนายาว', 'alpha': 'คั'},
    'TH1046': <String, String>{'name': 'คลองสามวา', 'alpha': 'ค'},
    'TH1018': <String, String>{'name': 'คลองสาน', 'alpha': 'ค'},
    'TH1033': <String, String>{'name': 'คลองเตย', 'alpha': 'ค'},
    'TH1041': <String, String>{'name': 'หลักสี่', 'alpha': 'ห'},
    'TH1011': <String, String>{'name': 'ลาดกระบัง', 'alpha': 'ล'},
    'TH1038': <String, String>{'name': 'ลาดพร้าว', 'alpha': 'ล'},
    'TH1010': <String, String>{'name': 'มีนบุรี', 'alpha': 'มี'},
    'TH1003': <String, String>{'name': 'หนองจอก', 'alpha': 'ห'},
    'TH1023': <String, String>{'name': 'หนองแขม', 'alpha': 'ห'},
    'TH1007': <String, String>{'name': 'ปทุมวัน', 'alpha': 'ป'},
    'TH1022': <String, String>{'name': 'ภาษีเจริญ', 'alpha': 'ภ'},
    'TH1014': <String, String>{'name': 'พญาไท', 'alpha': 'พ'},
    'TH1009': <String, String>{'name': 'พระโขนง', 'alpha': 'พ'},
    'TH1001': <String, String>{'name': 'พระนคร', 'alpha': 'พ'},
    'TH1008': <String, String>{'name': 'ป้อมปราบศัตรูพ่า', 'alpha': 'ป้'},
    'TH1032': <String, String>{'name': 'ประเวศ', 'alpha': 'ป'},
    'TH1024': <String, String>{'name': 'ราษฎร์บูรณะ', 'alpha': 'ร'},
    'TH1037': <String, String>{'name': 'ราชเทวี', 'alpha': 'ร'},
    'TH1042': <String, String>{'name': 'สายไหม', 'alpha': 'ส'},
    'TH1013': <String, String>{'name': 'สัมพันธวงศ์', 'alpha': 'สั'},
    'TH1044': <String, String>{'name': 'สะพานสูง', 'alpha': 'ส'},
    'TH1028': <String, String>{'name': 'สาทร', 'alpha': 'ส'},
    'TH1034': <String, String>{'name': 'สวนหลวง', 'alpha': 'ส'},
    'TH1019': <String, String>{'name': 'ตลิ่งชัน', 'alpha': 'ต'},
    'TH1048': <String, String>{'name': 'ทวีวัฒนา', 'alpha': 'ท'},
    'TH1015': <String, String>{'name': 'ธนบุรี', 'alpha': 'ธ'},
    'TH1049': <String, String>{'name': 'ทุ่งครุ', 'alpha': 'ทุ่'},
    'TH1039': <String, String>{'name': 'วัฒนา', 'alpha': 'วั'},
    'TH1045': <String, String>{'name': 'วังทองหลาง', 'alpha': 'วั'},
    'TH1012': <String, String>{'name': 'ยานนาวา', 'alpha': 'ย'}
  },
  'TH11': <String, Map<String, String>>{
    'TH1102': <String, String>{'name': 'บางบ่อ', 'alpha': 'บ'},
    'TH1103': <String, String>{'name': 'บางพลี', 'alpha': 'บ'},
    'TH1106': <String, String>{'name': 'บางเสาธง', 'alpha': 'บ'},
    'TH1101': <String, String>{'name': 'เมืองสมุทรปราการ', 'alpha': 'เ'},
    'TH1104': <String, String>{'name': 'พระประแดง', 'alpha': 'พ'},
    'TH1105': <String, String>{'name': 'พระสมุทรเจดีย์', 'alpha': 'พ'}
  },
  'TH12': <String, Map<String, String>>{
    'TH1204': <String, String>{'name': 'บางบัวทอง', 'alpha': 'บ'},
    'TH1202': <String, String>{'name': 'บางกรวย', 'alpha': 'บ'},
    'TH1203': <String, String>{'name': 'บางใหญ่', 'alpha': 'บ'},
    'TH1201': <String, String>{'name': 'เมืองนนทบุรี', 'alpha': 'เ'},
    'TH1206': <String, String>{'name': 'ปากเกร็ด', 'alpha': 'ป'},
    'TH1205': <String, String>{'name': 'ไทรน้อย', 'alpha': 'ไ'}
  },
  'TH13': <String, Map<String, String>>{
    'TH1302': <String, String>{'name': 'คลองหลวง', 'alpha': 'ค'},
    'TH1306': <String, String>{'name': 'ลำลูกกา', 'alpha': 'ลำ'},
    'TH1305': <String, String>{'name': 'ลาดหลุมแก้ว', 'alpha': 'ล'},
    'TH1301': <String, String>{'name': 'เมืองปทุมธานี', 'alpha': 'เ'},
    'TH1304': <String, String>{'name': 'หนองเสือ', 'alpha': 'ห'},
    'TH1307': <String, String>{'name': 'สามโคก', 'alpha': 'ส'},
    'TH1303': <String, String>{'name': 'ธัญบุรี', 'alpha': 'ธั'}
  },
  'TH14': <String, Map<String, String>>{
    'TH1416': <String, String>{'name': 'บ้านแพรก', 'alpha': 'บ้'},
    'TH1405': <String, String>{'name': 'บางบาล', 'alpha': 'บ'},
    'TH1406': <String, String>{'name': 'บางปะอิน', 'alpha': 'บ'},
    'TH1407': <String, String>{'name': 'บางปะหัน', 'alpha': 'บ'},
    'TH1404': <String, String>{'name': 'บางไทร', 'alpha': 'บ'},
    'TH1413': <String, String>{'name': 'บางซ้าย', 'alpha': 'บ'},
    'TH1410': <String, String>{'name': 'ลาดบัวหลวง', 'alpha': 'ล'},
    'TH1415': <String, String>{'name': 'มหาราช', 'alpha': 'ม'},
    'TH1403': <String, String>{'name': 'นครหลวง', 'alpha': 'น'},
    'TH1409': <String, String>{'name': 'ภาชี', 'alpha': 'ภ'},
    'TH1408': <String, String>{'name': 'ผักไห่', 'alpha': 'ผั'},
    'TH1401': <String, String>{'name': 'พระนครศรีอยุธยา', 'alpha': 'พ'},
    'TH1412': <String, String>{'name': 'เสนา', 'alpha': 'เ'},
    'TH1402': <String, String>{'name': 'ท่าเรือ', 'alpha': 'ท่'},
    'TH1414': <String, String>{'name': 'อุทัย', 'alpha': 'อุ'},
    'TH1411': <String, String>{'name': 'วังน้อย', 'alpha': 'วั'}
  },
  'TH15': <String, Map<String, String>>{
    'TH1502': <String, String>{'name': 'ไชโย', 'alpha': 'ไ'},
    'TH1501': <String, String>{'name': 'เมืองอ่างทอง', 'alpha': 'เ'},
    'TH1503': <String, String>{'name': 'ป่าโมก', 'alpha': 'ป่'},
    'TH1504': <String, String>{'name': 'โพธิ์ทอง', 'alpha': 'โ'},
    'TH1507': <String, String>{'name': 'สามโก้', 'alpha': 'ส'},
    'TH1505': <String, String>{'name': 'แสวงหา', 'alpha': 'แ'},
    'TH1506': <String, String>{'name': 'วิเศษชัยชาญ', 'alpha': 'วิ'}
  },
  'TH16': <String, Map<String, String>>{
    'TH1606': <String, String>{'name': 'บ้านหมี่', 'alpha': 'บ้'},
    'TH1604': <String, String>{'name': 'ชัยบาดาล', 'alpha': 'ชั'},
    'TH1609': <String, String>{'name': 'โคกเจริญ', 'alpha': 'โ'},
    'TH1603': <String, String>{'name': 'โคกสำโรง', 'alpha': 'โ'},
    'TH1610': <String, String>{'name': 'ลำสนธิ', 'alpha': 'ลำ'},
    'TH1601': <String, String>{'name': 'เมืองลพบุรี', 'alpha': 'เ'},
    'TH1611': <String, String>{'name': 'หนองม่วง', 'alpha': 'ห'},
    'TH1602': <String, String>{'name': 'พัฒนานิคม', 'alpha': 'พั'},
    'TH1608': <String, String>{'name': 'สระโบสถ์', 'alpha': 'ส'},
    'TH1607': <String, String>{'name': 'ท่าหลวง', 'alpha': 'ท่'},
    'TH1605': <String, String>{'name': 'ท่าวุ้ง', 'alpha': 'ท่'}
  },
  'TH17': <String, Map<String, String>>{
    'TH1702': <String, String>{'name': 'บางระจัน', 'alpha': 'บ'},
    'TH1706': <String, String>{'name': 'อินทร์บุรี', 'alpha': 'อิ'},
    'TH1703': <String, String>{'name': 'ค่ายบางระจัน', 'alpha': 'ค่'},
    'TH1701': <String, String>{'name': 'เมืองสิงห์บุรี', 'alpha': 'เ'},
    'TH1704': <String, String>{'name': 'พรหมบุรี', 'alpha': 'พ'},
    'TH1705': <String, String>{'name': 'ท่าช้าง', 'alpha': 'ท่'}
  },
  'TH18': <String, Map<String, String>>{
    'TH1806': <String, String>{'name': 'หันคา', 'alpha': 'หั'},
    'TH1802': <String, String>{'name': 'มโนรมย์', 'alpha': 'ม'},
    'TH1801': <String, String>{'name': 'เมืองชัยนาท', 'alpha': 'เ'},
    'TH1808': <String, String>{'name': 'เนินขาม', 'alpha': 'เ'},
    'TH1807': <String, String>{'name': 'หนองมะโมง', 'alpha': 'ห'},
    'TH1805': <String, String>{'name': 'สรรคบุรี', 'alpha': 'ส'},
    'TH1804': <String, String>{'name': 'สรรพยา', 'alpha': 'ส'},
    'TH1803': <String, String>{'name': 'วัดสิงห์', 'alpha': 'วั'}
  },
  'TH19': <String, Map<String, String>>{
    'TH1906': <String, String>{'name': 'บ้านหมอ', 'alpha': 'บ้'},
    'TH1913': <String, String>{'name': 'เฉลิมพระเกียรติ', 'alpha': 'เ'},
    'TH1907': <String, String>{'name': 'ดอนพุด', 'alpha': 'ด'},
    'TH1902': <String, String>{'name': 'แก่งคอย', 'alpha': 'แ'},
    'TH1911': <String, String>{'name': 'มวกเหล็ก', 'alpha': 'ม'},
    'TH1901': <String, String>{'name': 'เมืองสระบุรี', 'alpha': 'เ'},
    'TH1908': <String, String>{'name': 'หนองโดน', 'alpha': 'ห'},
    'TH1903': <String, String>{'name': 'หนองแค', 'alpha': 'ห'},
    'TH1905': <String, String>{'name': 'หนองแซง', 'alpha': 'ห'},
    'TH1909': <String, String>{'name': 'พระพุทธบาท', 'alpha': 'พ'},
    'TH1910': <String, String>{'name': 'เสาไห้', 'alpha': 'เ'},
    'TH1912': <String, String>{'name': 'วังม่วง', 'alpha': 'วั'},
    'TH1904': <String, String>{'name': 'วิหารแดง', 'alpha': 'วิ'}
  },
  'TH20': <String, Map<String, String>>{
    'TH2002': <String, String>{'name': 'บ้านบึง', 'alpha': 'บ้'},
    'TH2004': <String, String>{'name': 'บางละมุง', 'alpha': 'บ'},
    'TH2010': <String, String>{'name': 'บ่อทอง', 'alpha': 'บ่'},
    'TH2011': <String, String>{'name': 'เกาะจันทร์', 'alpha': 'เ'},
    'TH2008': <String, String>{'name': 'เกาะสีชัง', 'alpha': 'เ'},
    'TH2001': <String, String>{'name': 'เมืองชลบุรี', 'alpha': 'เ'},
    'TH2003': <String, String>{'name': 'หนองใหญ่', 'alpha': 'ห'},
    'TH2005': <String, String>{'name': 'พานทอง', 'alpha': 'พ'},
    'TH2006': <String, String>{'name': 'พนัสนิคม', 'alpha': 'พ'},
    'TH2009': <String, String>{'name': 'สัตหีบ', 'alpha': 'สั'},
    'TH2007': <String, String>{'name': 'ศรีราชา', 'alpha': 'ศ'}
  },
  'TH21': <String, Map<String, String>>{
    'TH2102': <String, String>{'name': 'บ้านฉาง', 'alpha': 'บ้'},
    'TH2105': <String, String>{'name': 'บ้านค่าย', 'alpha': 'บ้'},
    'TH2107': <String, String>{'name': 'เขาชะเมา', 'alpha': 'เ'},
    'TH2103': <String, String>{'name': 'แกลง', 'alpha': 'แ'},
    'TH2101': <String, String>{'name': 'เมืองระยอง', 'alpha': 'เ'},
    'TH2108': <String, String>{'name': 'นิคมพัฒนา', 'alpha': 'นิ'},
    'TH2106': <String, String>{'name': 'ปลวกแดง', 'alpha': 'ป'},
    'TH2104': <String, String>{'name': 'วังจันทร์', 'alpha': 'วั'}
  },
  'TH22': <String, Map<String, String>>{
    'TH2208': <String, String>{'name': 'แก่งหางแมว', 'alpha': 'แ'},
    'TH2210': <String, String>{'name': 'เขาคิชฌกูฏ', 'alpha': 'เ'},
    'TH2202': <String, String>{'name': 'ขลุง', 'alpha': 'ข'},
    'TH2206': <String, String>{'name': 'แหลมสิงห์', 'alpha': 'แ'},
    'TH2205': <String, String>{'name': 'มะขาม', 'alpha': 'ม'},
    'TH2201': <String, String>{'name': 'เมืองจันทบุรี', 'alpha': 'เ'},
    'TH2209': <String, String>{'name': 'นายายอาม', 'alpha': 'น'},
    'TH2204': <String, String>{'name': 'โป่งน้ำร้อน', 'alpha': 'โ'},
    'TH2207': <String, String>{'name': 'สอยดาว', 'alpha': 'ส'},
    'TH2203': <String, String>{'name': 'ท่าใหม่', 'alpha': 'ท่'}
  },
  'TH23': <String, Map<String, String>>{
    'TH2304': <String, String>{'name': 'บ่อไร่', 'alpha': 'บ่'},
    'TH2303': <String, String>{'name': 'เขาสมิง', 'alpha': 'เ'},
    'TH2302': <String, String>{'name': 'คลองใหญ่', 'alpha': 'ค'},
    'TH2307': <String, String>{'name': 'เกาะช้าง', 'alpha': 'เ'},
    'TH2306': <String, String>{'name': 'เกาะกูด', 'alpha': 'เ'},
    'TH2305': <String, String>{'name': 'แหลมงอบ', 'alpha': 'แ'},
    'TH2301': <String, String>{'name': 'เมืองตราด', 'alpha': 'เ'}
  },
  'TH24': <String, Map<String, String>>{
    'TH2405': <String, String>{'name': 'บ้านโพธิ์', 'alpha': 'บ้'},
    'TH2402': <String, String>{'name': 'บางคล้า', 'alpha': 'บ'},
    'TH2403': <String, String>{'name': 'บางน้ำเปรี้ยว', 'alpha': 'บ'},
    'TH2404': <String, String>{'name': 'บางปะกง', 'alpha': 'บ'},
    'TH2411': <String, String>{'name': 'คลองเขื่อน', 'alpha': 'ค'},
    'TH2401': <String, String>{'name': 'เมืองฉะเชิงเทรา', 'alpha': 'เ'},
    'TH2406': <String, String>{'name': 'พนมสารคาม', 'alpha': 'พ'},
    'TH2409': <String, String>{'name': 'แปลงยาว', 'alpha': 'แ'},
    'TH2407': <String, String>{'name': 'ราชสาส์น', 'alpha': 'ร'},
    'TH2408': <String, String>{'name': 'สนามชัยเขต', 'alpha': 'ส'},
    'TH2410': <String, String>{'name': 'ท่าตะเกียบ', 'alpha': 'ท่'}
  },
  'TH25': <String, Map<String, String>>{
    'TH2506': <String, String>{'name': 'บ้านสร้าง', 'alpha': 'บ้'},
    'TH2502': <String, String>{'name': 'กบินทร์บุรี', 'alpha': 'ก'},
    'TH2501': <String, String>{'name': 'เมืองปราจีนบุรี', 'alpha': 'เ'},
    'TH2503': <String, String>{'name': 'นาดี', 'alpha': 'น'},
    'TH2507': <String, String>{'name': 'ประจันตคาม', 'alpha': 'ป'},
    'TH2508': <String, String>{'name': 'ศรีมหาโพธิ', 'alpha': 'ศ'},
    'TH2509': <String, String>{'name': 'ศรีมโหสถ', 'alpha': 'ศ'}
  },
  'TH26': <String, Map<String, String>>{
    'TH2603': <String, String>{'name': 'บ้านนา', 'alpha': 'บ้'},
    'TH2601': <String, String>{'name': 'เมืองนครนายก', 'alpha': 'เ'},
    'TH2604': <String, String>{'name': 'องครักษ์', 'alpha': 'อ'},
    'TH2602': <String, String>{'name': 'ปากพลี', 'alpha': 'ป'}
  },
  'TH27': <String, Map<String, String>>{
    'TH2706': <String, String>{'name': 'อรัญประเทศ', 'alpha': 'อ'},
    'TH2707': <String, String>{'name': 'เขาฉกรรจ์', 'alpha': 'เ'},
    'TH2702': <String, String>{'name': 'คลองหาด', 'alpha': 'ค'},
    'TH2708': <String, String>{'name': 'โคกสูง', 'alpha': 'โ'},
    'TH2701': <String, String>{'name': 'เมืองสระแก้ว', 'alpha': 'เ'},
    'TH2703': <String, String>{'name': 'ตาพระยา', 'alpha': 'ต'},
    'TH2704': <String, String>{'name': 'วังน้ำเย็น', 'alpha': 'วั'},
    'TH2709': <String, String>{'name': 'วังสมบูรณ์', 'alpha': 'วั'},
    'TH2705': <String, String>{'name': 'วัฒนานคร', 'alpha': 'วั'}
  },
  'TH30': <String, Map<String, String>>{
    'TH3005': <String, String>{'name': 'บ้านเหลื่อม', 'alpha': 'บ้'},
    'TH3030': <String, String>{'name': 'บัวลาย', 'alpha': 'บั'},
    'TH3012': <String, String>{'name': 'บัวใหญ่', 'alpha': 'บั'},
    'TH3006': <String, String>{'name': 'จักราช', 'alpha': 'จั'},
    'TH3032': <String, String>{'name': 'เฉลิมพระเกียรติ', 'alpha': 'เ'},
    'TH3007': <String, String>{'name': 'โชคชัย', 'alpha': 'โ'},
    'TH3017': <String, String>{'name': 'ชุมพวง', 'alpha': 'ชุ'},
    'TH3008': <String, String>{'name': 'ด่านขุนทด', 'alpha': 'ด่'},
    'TH3016': <String, String>{'name': 'ห้วยแถลง', 'alpha': 'ห้'},
    'TH3023': <String, String>{'name': 'แก้งสนามนาง', 'alpha': 'แ'},
    'TH3011': <String, String>{'name': 'ขามสะแกแสง', 'alpha': 'ข'},
    'TH3019': <String, String>{'name': 'ขามทะเลสอ', 'alpha': 'ข'},
    'TH3002': <String, String>{'name': 'ครบุรี', 'alpha': 'ค'},
    'TH3004': <String, String>{'name': 'คง', 'alpha': 'ค'},
    'TH3029': <String, String>{'name': 'ลำทะเมนชัย', 'alpha': 'ลำ'},
    'TH3001': <String, String>{'name': 'เมืองนครราชสีมา', 'alpha': 'เ'},
    'TH3027': <String, String>{'name': 'เมืองยาง', 'alpha': 'เ'},
    'TH3024': <String, String>{'name': 'โนนแดง', 'alpha': 'โ'},
    'TH3010': <String, String>{'name': 'โนนสูง', 'alpha': 'โ'},
    'TH3009': <String, String>{'name': 'โนนไทย', 'alpha': 'โ'},
    'TH3022': <String, String>{'name': 'หนองบุญมาก', 'alpha': 'ห'},
    'TH3021': <String, String>{'name': 'ปากช่อง', 'alpha': 'ป'},
    'TH3014': <String, String>{'name': 'ปักธงชัย', 'alpha': 'ปั'},
    'TH3015': <String, String>{'name': 'พิมาย', 'alpha': 'พิ'},
    'TH3028': <String, String>{'name': 'พระทองคำ', 'alpha': 'พ'},
    'TH3013': <String, String>{'name': 'ประทาย', 'alpha': 'ป'},
    'TH3031': <String, String>{'name': 'สีดา', 'alpha': 'สี'},
    'TH3020': <String, String>{'name': 'สีคิ้ว', 'alpha': 'สี'},
    'TH3003': <String, String>{'name': 'เสิงสาง', 'alpha': 'เ'},
    'TH3018': <String, String>{'name': 'สูงเนิน', 'alpha': 'สู'},
    'TH3026': <String, String>{'name': 'เทพารักษ์', 'alpha': 'เ'},
    'TH3025': <String, String>{'name': 'วังน้ำเขียว', 'alpha': 'วั'}
  },
  'TH31': <String, Map<String, String>>{
    'TH3121': <String, String>{'name': 'บ้านด่าน', 'alpha': 'บ้'},
    'TH3108': <String, String>{'name': 'บ้านกรวด', 'alpha': 'บ้'},
    'TH3119': <String, String>{'name': 'บ้านใหม่ไชยพจน์', 'alpha': 'บ้'},
    'TH3123': <String, String>{'name': 'เฉลิมพระเกียรติ', 'alpha': 'เ'},
    'TH3118': <String, String>{'name': 'ชำนิ', 'alpha': 'ชำ'},
    'TH3116': <String, String>{'name': 'ห้วยราช', 'alpha': 'ห้'},
    'TH3122': <String, String>{'name': 'แคนดง', 'alpha': 'แ'},
    'TH3102': <String, String>{'name': 'คูเมือง', 'alpha': 'คู'},
    'TH3103': <String, String>{'name': 'กระสัง', 'alpha': 'ก'},
    'TH3106': <String, String>{'name': 'ละหานทราย', 'alpha': 'ล'},
    'TH3110': <String, String>{'name': 'ลำปลายมาศ', 'alpha': 'ลำ'},
    'TH3101': <String, String>{'name': 'เมืองบุรีรัมย์', 'alpha': 'เ'},
    'TH3113': <String, String>{'name': 'นาโพธิ์', 'alpha': 'น'},
    'TH3104': <String, String>{'name': 'นางรอง', 'alpha': 'น'},
    'TH3120': <String, String>{'name': 'โนนดินแดง', 'alpha': 'โ'},
    'TH3117': <String, String>{'name': 'โนนสุวรรณ', 'alpha': 'โ'},
    'TH3114': <String, String>{'name': 'หนองหงส์', 'alpha': 'ห'},
    'TH3105': <String, String>{'name': 'หนองกี่', 'alpha': 'ห'},
    'TH3112': <String, String>{'name': 'ปะคำ', 'alpha': 'ป'},
    'TH3115': <String, String>{'name': 'พลับพลาชัย', 'alpha': 'พ'},
    'TH3109': <String, String>{'name': 'พุทไธสง', 'alpha': 'พุ'},
    'TH3107': <String, String>{'name': 'ประโคนชัย', 'alpha': 'ป'},
    'TH3111': <String, String>{'name': 'สตึก', 'alpha': 'ส'}
  },
  'TH32': <String, Map<String, String>>{
    'TH3213': <String, String>{'name': 'บัวเชด', 'alpha': 'บั'},
    'TH3204': <String, String>{'name': 'จอมพระ', 'alpha': 'จ'},
    'TH3202': <String, String>{'name': 'ชุมพลบุรี', 'alpha': 'ชุ'},
    'TH3206': <String, String>{'name': 'กาบเชิง', 'alpha': 'ก'},
    'TH3216': <String, String>{'name': 'เขวาสินรินทร์', 'alpha': 'เ'},
    'TH3211': <String, String>{'name': 'ลำดวน', 'alpha': 'ลำ'},
    'TH3201': <String, String>{'name': 'เมืองสุรินทร์', 'alpha': 'เ'},
    'TH3217': <String, String>{'name': 'โนนนารายณ์', 'alpha': 'โ'},
    'TH3214': <String, String>{'name': 'พนมดงรัก', 'alpha': 'พ'},
    'TH3205': <String, String>{'name': 'ปราสาท', 'alpha': 'ป'},
    'TH3207': <String, String>{'name': 'รัตนบุรี', 'alpha': 'รั'},
    'TH3212': <String, String>{'name': 'สำโรงทาบ', 'alpha': 'สำ'},
    'TH3210': <String, String>{'name': 'สังขะ', 'alpha': 'สั'},
    'TH3208': <String, String>{'name': 'สนม', 'alpha': 'ส'},
    'TH3215': <String, String>{'name': 'ศรีณรงค์', 'alpha': 'ศ'},
    'TH3209': <String, String>{'name': 'ศีขรภูมิ', 'alpha': 'ศี'},
    'TH3203': <String, String>{'name': 'ท่าตูม', 'alpha': 'ท่'}
  },
  'TH33': <String, Map<String, String>>{
    'TH3319': <String, String>{'name': 'เบญจลักษ์', 'alpha': 'เ'},
    'TH3311': <String, String>{'name': 'บึงบูรพ์', 'alpha': 'บึ'},
    'TH3312': <String, String>{'name': 'ห้วยทับทัน', 'alpha': 'ห้'},
    'TH3304': <String, String>{'name': 'กันทรลักษ์', 'alpha': 'กั'},
    'TH3303': <String, String>{'name': 'กันทรารมย์', 'alpha': 'กั'},
    'TH3305': <String, String>{'name': 'ขุขันธ์', 'alpha': 'ขุ'},
    'TH3308': <String, String>{'name': 'ขุนหาญ', 'alpha': 'ขุ'},
    'TH3318': <String, String>{'name': 'เมืองจันทร์', 'alpha': 'เ'},
    'TH3301': <String, String>{'name': 'เมืองศรีสะเกษ', 'alpha': 'เ'},
    'TH3315': <String, String>{'name': 'น้ำเกลี้ยง', 'alpha': 'น้ำ'},
    'TH3313': <String, String>{'name': 'โนนคูณ', 'alpha': 'โ'},
    'TH3320': <String, String>{'name': 'พยุห์', 'alpha': 'พ'},
    'TH3321': <String, String>{'name': 'โพธิ์ศรีสุวรรณ', 'alpha': 'โ'},
    'TH3306': <String, String>{'name': 'ไพรบึง', 'alpha': 'ไ'},
    'TH3317': <String, String>{'name': 'ภูสิงห์', 'alpha': 'ภู'},
    'TH3307': <String, String>{'name': 'ปรางค์กู่', 'alpha': 'ป'},
    'TH3309': <String, String>{'name': 'ราษีไศล', 'alpha': 'ร'},
    'TH3314': <String, String>{'name': 'ศรีรัตนะ', 'alpha': 'ศ'},
    'TH3322': <String, String>{'name': 'ศิลาลาด', 'alpha': 'ศิ'},
    'TH3310': <String, String>{'name': 'อุทุมพรพิสัย', 'alpha': 'อุ'},
    'TH3316': <String, String>{'name': 'วังหิน', 'alpha': 'วั'},
    'TH3302': <String, String>{'name': 'ยางชุมน้อย', 'alpha': 'ย'}
  },
  'TH34': <String, Map<String, String>>{
    'TH3410': <String, String>{'name': 'บุณฑริก', 'alpha': 'บุ'},
    'TH3407': <String, String>{'name': 'เดชอุดม', 'alpha': 'เ'},
    'TH3424': <String, String>{'name': 'ดอนมดแดง', 'alpha': 'ด'},
    'TH3405': <String, String>{'name': 'เขมราฐ', 'alpha': 'เ'},
    'TH3403': <String, String>{'name': 'โขงเจียม', 'alpha': 'โ'},
    'TH3404': <String, String>{'name': 'เขื่องใน', 'alpha': 'เ'},
    'TH3412': <String, String>{'name': 'กุดข้าวปุ้น', 'alpha': 'กุ'},
    'TH3431': <String, String>{'name': 'เหล่าเสือโก้ก', 'alpha': 'เ'},
    'TH3414': <String, String>{'name': 'ม่วงสามสิบ', 'alpha': 'ม่'},
    'TH3401': <String, String>{'name': 'เมืองอุบลราชธานี', 'alpha': 'เ'},
    'TH3408': <String, String>{'name': 'นาจะหลวย', 'alpha': 'น'},
    'TH3430': <String, String>{'name': 'นาตาล', 'alpha': 'น'},
    'TH3429': <String, String>{'name': 'นาเยีย', 'alpha': 'น'},
    'TH3433': <String, String>{'name': 'น้ำขุ่น', 'alpha': 'น้ำ'},
    'TH3409': <String, String>{'name': 'น้ำยืน', 'alpha': 'น้ำ'},
    'TH3419': <String, String>{'name': 'พิบูลมังสาหาร', 'alpha': 'พิ'},
    'TH3421': <String, String>{'name': 'โพธิ์ไทร', 'alpha': 'โ'},
    'TH3422': <String, String>{'name': 'สำโรง', 'alpha': 'สำ'},
    'TH3432': <String, String>{'name': 'สว่างวีระวงศ์', 'alpha': 'ส'},
    'TH3402': <String, String>{'name': 'ศรีเมืองใหม่', 'alpha': 'ศ'},
    'TH3425': <String, String>{'name': 'สิรินธร', 'alpha': 'สิ'},
    'TH3420': <String, String>{'name': 'ตาลสุม', 'alpha': 'ต'},
    'TH3426': <String, String>{'name': 'ทุ่งศรีอุดม', 'alpha': 'ทุ่'},
    'TH3411': <String, String>{'name': 'ตระการพืชผล', 'alpha': 'ต'},
    'TH3415': <String, String>{'name': 'วารินชำราบ', 'alpha': 'ว'}
  },
  'TH35': <String, Map<String, String>>{
    'TH3504': <String, String>{'name': 'คำเขื่อนแก้ว', 'alpha': 'คำ'},
    'TH3507': <String, String>{'name': 'ค้อวัง', 'alpha': 'ค้'},
    'TH3503': <String, String>{'name': 'กุดชุม', 'alpha': 'กุ'},
    'TH3508': <String, String>{'name': 'เลิงนกทา', 'alpha': 'เ'},
    'TH3506': <String, String>{'name': 'มหาชนะชัย', 'alpha': 'ม'},
    'TH3501': <String, String>{'name': 'เมืองยโสธร', 'alpha': 'เ'},
    'TH3505': <String, String>{'name': 'ป่าติ้ว', 'alpha': 'ป่'},
    'TH3502': <String, String>{'name': 'ทรายมูล', 'alpha': 'ท'},
    'TH3509': <String, String>{'name': 'ไทยเจริญ', 'alpha': 'ไ'}
  },
  'TH36': <String, Map<String, String>>{
    'TH3607': <String, String>{'name': 'บำเหน็จณรงค์', 'alpha': 'บำ'},
    'TH3602': <String, String>{'name': 'บ้านเขว้า', 'alpha': 'บ้'},
    'TH3611': <String, String>{'name': 'บ้านแท่น', 'alpha': 'บ้'},
    'TH3606': <String, String>{'name': 'จัตุรัส', 'alpha': 'จั'},
    'TH3612': <String, String>{'name': 'แก้งคร้อ', 'alpha': 'แ'},
    'TH3604': <String, String>{'name': 'เกษตรสมบูรณ์', 'alpha': 'เ'},
    'TH3613': <String, String>{'name': 'คอนสาร', 'alpha': 'ค'},
    'TH3603': <String, String>{'name': 'คอนสวรรค์', 'alpha': 'ค'},
    'TH3601': <String, String>{'name': 'เมืองชัยภูมิ', 'alpha': 'เ'},
    'TH3615': <String, String>{'name': 'เนินสง่า', 'alpha': 'เ'},
    'TH3605': <String, String>{'name': 'หนองบัวแดง', 'alpha': 'ห'},
    'TH3608': <String, String>{'name': 'หนองบัวระเหว', 'alpha': 'ห'},
    'TH3614': <String, String>{'name': 'ภักดีชุมพล', 'alpha': 'ภั'},
    'TH3610': <String, String>{'name': 'ภูเขียว', 'alpha': 'ภู'},
    'TH3616': <String, String>{'name': 'ซับใหญ่', 'alpha': 'ซั'},
    'TH3609': <String, String>{'name': 'เทพสถิต', 'alpha': 'เ'}
  },
  'TH37': <String, Map<String, String>>{
    'TH3702': <String, String>{'name': 'ชานุมาน', 'alpha': 'ช'},
    'TH3706': <String, String>{'name': 'หัวตะพาน', 'alpha': 'หั'},
    'TH3707': <String, String>{'name': 'ลืออำนาจ', 'alpha': 'ลื'},
    'TH3701': <String, String>{'name': 'เมืองอำนาจเจริญ', 'alpha': 'เ'},
    'TH3703': <String, String>{'name': 'ปทุมราชวงศา', 'alpha': 'ป'},
    'TH3704': <String, String>{'name': 'พนา', 'alpha': 'พ'},
    'TH3705': <String, String>{'name': 'เสนางคนิคม', 'alpha': 'เ'}
  },
  'TH38': <String, Map<String, String>>{
    'TH3806': <String, String>{'name': 'บึงโขงหลง', 'alpha': 'บึ'},
    'TH3808': <String, String>{'name': 'บุ่งคล้า', 'alpha': 'บุ่'},
    'TH3801': <String, String>{'name': 'เมืองบึงกาฬ', 'alpha': 'เ'},
    'TH3805': <String, String>{'name': 'ปากคาด', 'alpha': 'ป'},
    'TH3802': <String, String>{'name': 'พรเจริญ', 'alpha': 'พ'},
    'TH3804': <String, String>{'name': 'เซกา', 'alpha': 'เ'},
    'TH3807': <String, String>{'name': 'ศรีวิไล', 'alpha': 'ศ'},
    'TH3803': <String, String>{'name': 'โซ่พิสัย', 'alpha': 'โ'}
  },
  'TH39': <String, Map<String, String>>{
    'TH3901': <String, String>{'name': 'เมืองหนองบัวลำภู', 'alpha': 'เ'},
    'TH3902': <String, String>{'name': 'นากลาง', 'alpha': 'น'},
    'TH3906': <String, String>{'name': 'นาวัง', 'alpha': 'น'},
    'TH3903': <String, String>{'name': 'โนนสัง', 'alpha': 'โ'},
    'TH3904': <String, String>{'name': 'ศรีบุญเรือง', 'alpha': 'ศ'},
    'TH3905': <String, String>{'name': 'สุวรรณคูหา', 'alpha': 'สุ'}
  },
  'TH40': <String, Map<String, String>>{
    'TH4002': <String, String>{'name': 'บ้านฝาง', 'alpha': 'บ้'},
    'TH4024': <String, String>{'name': 'บ้านแฮด', 'alpha': 'บ้'},
    'TH4010': <String, String>{'name': 'บ้านไผ่', 'alpha': 'บ้'},
    'TH4018': <String, String>{'name': 'ชนบท', 'alpha': 'ช'},
    'TH4005': <String, String>{'name': 'ชุมแพ', 'alpha': 'ชุ'},
    'TH4019': <String, String>{'name': 'เขาสวนกวาง', 'alpha': 'เ'},
    'TH4022': <String, String>{'name': 'โคกโพธิ์ไชย', 'alpha': 'โ'},
    'TH4009': <String, String>{'name': 'กระนวน', 'alpha': 'ก'},
    'TH4017': <String, String>{'name': 'มัญจาคีรี', 'alpha': 'มั'},
    'TH4001': <String, String>{'name': 'เมืองขอนแก่น', 'alpha': 'เ'},
    'TH4007': <String, String>{'name': 'น้ำพอง', 'alpha': 'น้ำ'},
    'TH4025': <String, String>{'name': 'โนนศิลา', 'alpha': 'โ'},
    'TH4023': <String, String>{'name': 'หนองนาคำ', 'alpha': 'ห'},
    'TH4004': <String, String>{'name': 'หนองเรือ', 'alpha': 'ห'},
    'TH4015': <String, String>{'name': 'หนองสองห้อง', 'alpha': 'ห'},
    'TH4012': <String, String>{'name': 'พล', 'alpha': 'พ'},
    'TH4003': <String, String>{'name': 'พระยืน', 'alpha': 'พ'},
    'TH4020': <String, String>{'name': 'ภูผาม่าน', 'alpha': 'ภู'},
    'TH4016': <String, String>{'name': 'ภูเวียง', 'alpha': 'ภู'},
    'TH4011': <String, String>{'name': 'เปือยน้อย', 'alpha': 'เ'},
    'TH4021': <String, String>{'name': 'ซำสูง', 'alpha': 'ซำ'},
    'TH4006': <String, String>{'name': 'สีชมพู', 'alpha': 'สี'},
    'TH4008': <String, String>{'name': 'อุบลรัตน์', 'alpha': 'อุ'},
    'TH4014': <String, String>{'name': 'แวงน้อย', 'alpha': 'แ'},
    'TH4013': <String, String>{'name': 'แวงใหญ่', 'alpha': 'แ'},
    'TH4029': <String, String>{'name': 'เวียงเก่า', 'alpha': 'เ'}
  },
  'TH41': <String, Map<String, String>>{
    'TH4111': <String, String>{'name': 'บ้านดุง', 'alpha': 'บ้'},
    'TH4117': <String, String>{'name': 'บ้านผือ', 'alpha': 'บ้'},
    'TH4108': <String, String>{'name': 'ไชยวาน', 'alpha': 'ไ'},
    'TH4124': <String, String>{'name': 'กู่แก้ว', 'alpha': 'กู่'},
    'TH4104': <String, String>{'name': 'กุมภวาปี', 'alpha': 'กุ'},
    'TH4102': <String, String>{'name': 'กุดจับ', 'alpha': 'กุ'},
    'TH4101': <String, String>{'name': 'เมืองอุดรธานี', 'alpha': 'เ'},
    'TH4122': <String, String>{'name': 'นายูง', 'alpha': 'น'},
    'TH4118': <String, String>{'name': 'น้ำโสม', 'alpha': 'น้ำ'},
    'TH4105': <String, String>{'name': 'โนนสะอาด', 'alpha': 'โ'},
    'TH4106': <String, String>{'name': 'หนองหาน', 'alpha': 'ห'},
    'TH4121': <String, String>{'name': 'หนองแสง', 'alpha': 'ห'},
    'TH4103': <String, String>{'name': 'หนองวัวซอ', 'alpha': 'ห'},
    'TH4119': <String, String>{'name': 'เพ็ญ', 'alpha': 'เ'},
    'TH4123': <String, String>{'name': 'พิบูลย์รักษ์', 'alpha': 'พิ'},
    'TH4125': <String, String>{'name': 'ประจักษ์ศิลปาคม', 'alpha': 'ป'},
    'TH4120': <String, String>{'name': 'สร้างคอม', 'alpha': 'ส'},
    'TH4109': <String, String>{'name': 'ศรีธาตุ', 'alpha': 'ศ'},
    'TH4107': <String, String>{'name': 'ทุ่งฝน', 'alpha': 'ทุ่'},
    'TH4110': <String, String>{'name': 'วังสามหมอ', 'alpha': 'วั'}
  },
  'TH42': <String, Map<String, String>>{
    'TH4203': <String, String>{'name': 'เชียงคาน', 'alpha': 'เ'},
    'TH4205': <String, String>{'name': 'ด่านซ้าย', 'alpha': 'ด่'},
    'TH4213': <String, String>{'name': 'เอราวัณ', 'alpha': 'เ'},
    'TH4201': <String, String>{'name': 'เมืองเลย', 'alpha': 'เ'},
    'TH4202': <String, String>{'name': 'นาด้วง', 'alpha': 'น'},
    'TH4206': <String, String>{'name': 'นาแห้ว', 'alpha': 'น'},
    'TH4214': <String, String>{'name': 'หนองหิน', 'alpha': 'ห'},
    'TH4204': <String, String>{'name': 'ปากชม', 'alpha': 'ป'},
    'TH4212': <String, String>{'name': 'ผาขาว', 'alpha': 'ผ'},
    'TH4210': <String, String>{'name': 'ภูกระดึง', 'alpha': 'ภู'},
    'TH4211': <String, String>{'name': 'ภูหลวง', 'alpha': 'ภู'},
    'TH4207': <String, String>{'name': 'ภูเรือ', 'alpha': 'ภู'},
    'TH4208': <String, String>{'name': 'ท่าลี่', 'alpha': 'ท่'},
    'TH4209': <String, String>{'name': 'วังสะพุง', 'alpha': 'วั'}
  },
  'TH43': <String, Map<String, String>>{
    'TH4315': <String, String>{'name': 'เฝ้าไร่', 'alpha': 'เ'},
    'TH4301': <String, String>{'name': 'เมืองหนองคาย', 'alpha': 'เ'},
    'TH4317': <String, String>{'name': 'โพธิ์ตาก', 'alpha': 'โ'},
    'TH4305': <String, String>{'name': 'โพนพิสัย', 'alpha': 'โ'},
    'TH4316': <String, String>{'name': 'รัตนวาปี', 'alpha': 'รั'},
    'TH4314': <String, String>{'name': 'สระใคร', 'alpha': 'ส'},
    'TH4308': <String, String>{'name': 'สังคม', 'alpha': 'สั'},
    'TH4307': <String, String>{'name': 'ศรีเชียงใหม่', 'alpha': 'ศ'},
    'TH4302': <String, String>{'name': 'ท่าบ่อ', 'alpha': 'ท่'}
  },
  'TH44': <String, Map<String, String>>{
    'TH4406': <String, String>{'name': 'บรบือ', 'alpha': 'บ'},
    'TH4405': <String, String>{'name': 'เชียงยืน', 'alpha': 'เ'},
    'TH4413': <String, String>{'name': 'ชื่นชม', 'alpha': 'ชื่'},
    'TH4402': <String, String>{'name': 'แกดำ', 'alpha': 'แ'},
    'TH4404': <String, String>{'name': 'กันทรวิชัย', 'alpha': 'กั'},
    'TH4403': <String, String>{'name': 'โกสุมพิสัย', 'alpha': 'โ'},
    'TH4412': <String, String>{'name': 'กุดรัง', 'alpha': 'กุ'},
    'TH4401': <String, String>{'name': 'เมืองมหาสารคาม', 'alpha': 'เ'},
    'TH4407': <String, String>{'name': 'นาเชือก', 'alpha': 'น'},
    'TH4410': <String, String>{'name': 'นาดูน', 'alpha': 'น'},
    'TH4408': <String, String>{'name': 'พยัคฆภูมิพิสัย', 'alpha': 'พ'},
    'TH4409': <String, String>{'name': 'วาปีปทุม', 'alpha': 'ว'},
    'TH4411': <String, String>{'name': 'ยางสีสุราช', 'alpha': 'ย'}
  },
  'TH45': <String, Map<String, String>>{
    'TH4514': <String, String>{'name': 'อาจสามารถ', 'alpha': 'อ'},
    'TH4517': <String, String>{'name': 'จังหาร', 'alpha': 'จั'},
    'TH4504': <String, String>{'name': 'จตุรพักตรพิมาน', 'alpha': 'จ'},
    'TH4518': <String, String>{'name': 'เชียงขวัญ', 'alpha': 'เ'},
    'TH4502': <String, String>{'name': 'เกษตรวิสัย', 'alpha': 'เ'},
    'TH4515': <String, String>{'name': 'เมยวดี', 'alpha': 'เ'},
    'TH4501': <String, String>{'name': 'เมืองร้อยเอ็ด', 'alpha': 'เ'},
    'TH4512': <String, String>{'name': 'เมืองสรวง', 'alpha': 'เ'},
    'TH4519': <String, String>{'name': 'หนองฮี', 'alpha': 'ห'},
    'TH4509': <String, String>{'name': 'หนองพอก', 'alpha': 'ห'},
    'TH4503': <String, String>{'name': 'ปทุมรัตต์', 'alpha': 'ป'},
    'TH4506': <String, String>{'name': 'พนมไพร', 'alpha': 'พ'},
    'TH4508': <String, String>{'name': 'โพธิ์ชัย', 'alpha': 'โ'},
    'TH4513': <String, String>{'name': 'โพนทราย', 'alpha': 'โ'},
    'TH4507': <String, String>{'name': 'โพนทอง', 'alpha': 'โ'},
    'TH4510': <String, String>{'name': 'เสลภูมิ', 'alpha': 'เ'},
    'TH4516': <String, String>{'name': 'ศรีสมเด็จ', 'alpha': 'ศ'},
    'TH4511': <String, String>{'name': 'สุวรรณภูมิ', 'alpha': 'สุ'},
    'TH4505': <String, String>{'name': 'ธวัชบุรี', 'alpha': 'ธ'},
    'TH4520': <String, String>{'name': 'ทุ่งเขาหลวง', 'alpha': 'ทุ่'}
  },
  'TH46': <String, Map<String, String>>{
    'TH4617': <String, String>{'name': 'ดอนจาน', 'alpha': 'ด'},
    'TH4608': <String, String>{'name': 'ห้วยเม็ก', 'alpha': 'ห้'},
    'TH4614': <String, String>{'name': 'ห้วยผึ้ง', 'alpha': 'ห้'},
    'TH4603': <String, String>{'name': 'กมลาไสย', 'alpha': 'ก'},
    'TH4610': <String, String>{'name': 'คำม่วง', 'alpha': 'คำ'},
    'TH4606': <String, String>{'name': 'เขาวง', 'alpha': 'เ'},
    'TH4618': <String, String>{'name': 'ฆ้องชัย', 'alpha': 'ฆ้'},
    'TH4605': <String, String>{'name': 'กุฉินารายณ์', 'alpha': 'กุ'},
    'TH4601': <String, String>{'name': 'เมืองกาฬสินธุ์', 'alpha': 'เ'},
    'TH4616': <String, String>{'name': 'นาคู', 'alpha': 'น'},
    'TH4602': <String, String>{'name': 'นามน', 'alpha': 'น'},
    'TH4612': <String, String>{'name': 'หนองกุงศรี', 'alpha': 'ห'},
    'TH4604': <String, String>{'name': 'ร่องคำ', 'alpha': 'ร่'},
    'TH4609': <String, String>{'name': 'สหัสขันธ์', 'alpha': 'ส'},
    'TH4615': <String, String>{'name': 'สามชัย', 'alpha': 'ส'},
    'TH4613': <String, String>{'name': 'สมเด็จ', 'alpha': 'ส'},
    'TH4611': <String, String>{'name': 'ท่าคันโท', 'alpha': 'ท่'},
    'TH4607': <String, String>{'name': 'ยางตลาด', 'alpha': 'ย'}
  },
  'TH47': <String, Map<String, String>>{
    'TH4711': <String, String>{'name': 'อากาศอำนวย', 'alpha': 'อ'},
    'TH4710': <String, String>{'name': 'บ้านม่วง', 'alpha': 'บ้'},
    'TH4716': <String, String>{'name': 'เจริญศิลป์', 'alpha': 'เ'},
    'TH4709': <String, String>{'name': 'คำตากล้า', 'alpha': 'คำ'},
    'TH4715': <String, String>{'name': 'โคกศรีสุพรรณ', 'alpha': 'โ'},
    'TH4702': <String, String>{'name': 'กุสุมาลย์', 'alpha': 'กุ'},
    'TH4703': <String, String>{'name': 'กุดบาก', 'alpha': 'กุ'},
    'TH4701': <String, String>{'name': 'เมืองสกลนคร', 'alpha': 'เ'},
    'TH4707': <String, String>{'name': 'นิคมน้ำอูน', 'alpha': 'นิ'},
    'TH4705': <String, String>{'name': 'พังโคน', 'alpha': 'พั'},
    'TH4704': <String, String>{'name': 'พรรณานิคม', 'alpha': 'พ'},
    'TH4717': <String, String>{'name': 'โพนนาแก้ว', 'alpha': 'โ'},
    'TH4718': <String, String>{'name': 'ภูพาน', 'alpha': 'ภู'},
    'TH4712': <String, String>{'name': 'สว่างแดนดิน', 'alpha': 'ส'},
    'TH4713': <String, String>{'name': 'ส่องดาว', 'alpha': 'ส่'},
    'TH4714': <String, String>{'name': 'เต่างอย', 'alpha': 'เ'},
    'TH4708': <String, String>{'name': 'วานรนิวาส', 'alpha': 'ว'},
    'TH4706': <String, String>{'name': 'วาริชภูมิ', 'alpha': 'ว'}
  },
  'TH48': <String, Map<String, String>>{
    'TH4804': <String, String>{'name': 'บ้านแพง', 'alpha': 'บ้'},
    'TH4801': <String, String>{'name': 'เมืองนครพนม', 'alpha': 'เ'},
    'TH4807': <String, String>{'name': 'นาแก', 'alpha': 'น'},
    'TH4811': <String, String>{'name': 'นาทม', 'alpha': 'น'},
    'TH4809': <String, String>{'name': 'นาหว้า', 'alpha': 'น'},
    'TH4810': <String, String>{'name': 'โพนสวรรค์', 'alpha': 'โ'},
    'TH4802': <String, String>{'name': 'ปลาปาก', 'alpha': 'ป'},
    'TH4806': <String, String>{'name': 'เรณูนคร', 'alpha': 'เ'},
    'TH4808': <String, String>{'name': 'ศรีสงคราม', 'alpha': 'ศ'},
    'TH4803': <String, String>{'name': 'ท่าอุเทน', 'alpha': 'ท่'},
    'TH4805': <String, String>{'name': 'ธาตุพนม', 'alpha': 'ธ'},
    'TH4812': <String, String>{'name': 'วังยาง', 'alpha': 'วั'}
  },
  'TH49': <String, Map<String, String>>{
    'TH4903': <String, String>{'name': 'ดอนตาล', 'alpha': 'ด'},
    'TH4904': <String, String>{'name': 'ดงหลวง', 'alpha': 'ด'},
    'TH4905': <String, String>{'name': 'คำชะอี', 'alpha': 'คำ'},
    'TH4901': <String, String>{'name': 'เมืองมุกดาหาร', 'alpha': 'เ'},
    'TH4902': <String, String>{'name': 'นิคมคำสร้อย', 'alpha': 'นิ'},
    'TH4907': <String, String>{'name': 'หนองสูง', 'alpha': 'ห'},
    'TH4906': <String, String>{'name': 'หว้านใหญ่', 'alpha': 'ห'}
  },
  'TH50': <String, Map<String, String>>{
    'TH5021': <String, String>{'name': 'ไชยปราการ', 'alpha': 'ไ'},
    'TH5004': <String, String>{'name': 'เชียงดาว', 'alpha': 'เ'},
    'TH5002': <String, String>{'name': 'จอมทอง', 'alpha': 'จ'},
    'TH5024': <String, String>{'name': 'ดอยหล่อ', 'alpha': 'ด'},
    'TH5005': <String, String>{'name': 'ดอยสะเก็ด', 'alpha': 'ด'},
    'TH5017': <String, String>{'name': 'ดอยเต่า', 'alpha': 'ด'},
    'TH5009': <String, String>{'name': 'ฝาง', 'alpha': 'ฝ'},
    'TH5025': <String, String>{'name': 'กัลยาณิวัฒนา', 'alpha': 'กั'},
    'TH5015': <String, String>{'name': 'หางดง', 'alpha': 'ห'},
    'TH5016': <String, String>{'name': 'ฮอด', 'alpha': 'ฮ'},
    'TH5010': <String, String>{'name': 'แม่อาย', 'alpha': 'แ'},
    'TH5003': <String, String>{'name': 'แม่แจ่ม', 'alpha': 'แ'},
    'TH5023': <String, String>{'name': 'แม่ออน', 'alpha': 'แ'},
    'TH5007': <String, String>{'name': 'แม่ริม', 'alpha': 'แ'},
    'TH5006': <String, String>{'name': 'แม่แตง', 'alpha': 'แ'},
    'TH5022': <String, String>{'name': 'แม่วาง', 'alpha': 'แ'},
    'TH5001': <String, String>{'name': 'เมืองเชียงใหม่', 'alpha': 'เ'},
    'TH5018': <String, String>{'name': 'อมก๋อย', 'alpha': 'อ'},
    'TH5011': <String, String>{'name': 'พร้าว', 'alpha': 'พ'},
    'TH5008': <String, String>{'name': 'สะเมิง', 'alpha': 'ส'},
    'TH5013': <String, String>{'name': 'สันกำแพง', 'alpha': 'สั'},
    'TH5012': <String, String>{'name': 'สันป่าตอง', 'alpha': 'สั'},
    'TH5014': <String, String>{'name': 'สันทราย', 'alpha': 'สั'},
    'TH5019': <String, String>{'name': 'สารภี', 'alpha': 'ส'},
    'TH5020': <String, String>{'name': 'เวียงแหง', 'alpha': 'เ'}
  },
  'TH51': <String, Map<String, String>>{
    'TH5103': <String, String>{'name': 'บ้านโฮ่ง', 'alpha': 'บ้'},
    'TH5107': <String, String>{'name': 'บ้านธิ', 'alpha': 'บ้'},
    'TH5104': <String, String>{'name': 'ลี้', 'alpha': 'ลี้'},
    'TH5102': <String, String>{'name': 'แม่ทา', 'alpha': 'แ'},
    'TH5101': <String, String>{'name': 'เมืองลำพูน', 'alpha': 'เ'},
    'TH5106': <String, String>{'name': 'ป่าซาง', 'alpha': 'ป่'},
    'TH5105': <String, String>{'name': 'ทุ่งหัวช้าง', 'alpha': 'ทุ่'},
    'TH5108': <String, String>{'name': 'เวียงหนองล่อง', 'alpha': 'เ'}
  },
  'TH52': <String, Map<String, String>>{
    'TH5206': <String, String>{'name': 'แจ้ห่ม', 'alpha': 'แ'},
    'TH5212': <String, String>{'name': 'ห้างฉัตร', 'alpha': 'ห้'},
    'TH5203': <String, String>{'name': 'เกาะคา', 'alpha': 'เ'},
    'TH5202': <String, String>{'name': 'แม่เมาะ', 'alpha': 'แ'},
    'TH5209': <String, String>{'name': 'แม่พริก', 'alpha': 'แ'},
    'TH5210': <String, String>{'name': 'แม่ทะ', 'alpha': 'แ'},
    'TH5201': <String, String>{'name': 'เมืองลำปาง', 'alpha': 'เ'},
    'TH5213': <String, String>{'name': 'เมืองปาน', 'alpha': 'เ'},
    'TH5205': <String, String>{'name': 'งาว', 'alpha': 'ง'},
    'TH5204': <String, String>{'name': 'เสริมงาม', 'alpha': 'เ'},
    'TH5211': <String, String>{'name': 'สบปราบ', 'alpha': 'ส'},
    'TH5208': <String, String>{'name': 'เถิน', 'alpha': 'เ'},
    'TH5207': <String, String>{'name': 'วังเหนือ', 'alpha': 'วั'}
  },
  'TH53': <String, Map<String, String>>{
    'TH5306': <String, String>{'name': 'บ้านโคก', 'alpha': 'บ้'},
    'TH5305': <String, String>{'name': 'ฟากท่า', 'alpha': 'ฟ'},
    'TH5308': <String, String>{'name': 'ลับแล', 'alpha': 'ลั'},
    'TH5301': <String, String>{'name': 'เมืองอุตรดิตถ์', 'alpha': 'เ'},
    'TH5304': <String, String>{'name': 'น้ำปาด', 'alpha': 'น้ำ'},
    'TH5307': <String, String>{'name': 'พิชัย', 'alpha': 'พิ'},
    'TH5303': <String, String>{'name': 'ท่าปลา', 'alpha': 'ท่'},
    'TH5309': <String, String>{'name': 'ทองแสนขัน', 'alpha': 'ท'},
    'TH5302': <String, String>{'name': 'ตรอน', 'alpha': 'ต'}
  },
  'TH54': <String, Map<String, String>>{
    'TH5405': <String, String>{'name': 'เด่นชัย', 'alpha': 'เ'},
    'TH5403': <String, String>{'name': 'ลอง', 'alpha': 'ล'},
    'TH5401': <String, String>{'name': 'เมืองแพร่', 'alpha': 'เ'},
    'TH5408': <String, String>{'name': 'หนองม่วงไข่', 'alpha': 'ห'},
    'TH5402': <String, String>{'name': 'ร้องกวาง', 'alpha': 'ร้'},
    'TH5406': <String, String>{'name': 'สอง', 'alpha': 'ส'},
    'TH5404': <String, String>{'name': 'สูงเม่น', 'alpha': 'สู'},
    'TH5407': <String, String>{'name': 'วังชิ้น', 'alpha': 'วั'}
  },
  'TH55': <String, Map<String, String>>{
    'TH5503': <String, String>{'name': 'บ้านหลวง', 'alpha': 'บ้'},
    'TH5512': <String, String>{'name': 'บ่อเกลือ', 'alpha': 'บ่'},
    'TH5515': <String, String>{'name': 'เฉลิมพระเกียรติ', 'alpha': 'เ'},
    'TH5509': <String, String>{'name': 'เชียงกลาง', 'alpha': 'เ'},
    'TH5502': <String, String>{'name': 'แม่จริม', 'alpha': 'แ'},
    'TH5501': <String, String>{'name': 'เมืองน่าน', 'alpha': 'เ'},
    'TH5510': <String, String>{'name': 'นาหมื่น', 'alpha': 'น'},
    'TH5504': <String, String>{'name': 'นาน้อย', 'alpha': 'น'},
    'TH5514': <String, String>{'name': 'ภูเพียง', 'alpha': 'ภู'},
    'TH5505': <String, String>{'name': 'ปัว', 'alpha': 'ปั'},
    'TH5511': <String, String>{'name': 'สันติสุข', 'alpha': 'สั'},
    'TH5513': <String, String>{'name': 'สองแคว', 'alpha': 'ส'},
    'TH5506': <String, String>{'name': 'ท่าวังผา', 'alpha': 'ท่'},
    'TH5508': <String, String>{'name': 'ทุ่งช้าง', 'alpha': 'ทุ่'},
    'TH5507': <String, String>{'name': 'เวียงสา', 'alpha': 'เ'}
  },
  'TH56': <String, Map<String, String>>{
    'TH5603': <String, String>{'name': 'เชียงคำ', 'alpha': 'เ'},
    'TH5604': <String, String>{'name': 'เชียงม่วน', 'alpha': 'เ'},
    'TH5602': <String, String>{'name': 'จุน', 'alpha': 'จุ'},
    'TH5605': <String, String>{'name': 'ดอกคำใต้', 'alpha': 'ด'},
    'TH5607': <String, String>{'name': 'แม่ใจ', 'alpha': 'แ'},
    'TH5601': <String, String>{'name': 'เมืองพะเยา', 'alpha': 'เ'},
    'TH5609': <String, String>{'name': 'ภูกามยาว', 'alpha': 'ภู'},
    'TH5608': <String, String>{'name': 'ภูซาง', 'alpha': 'ภู'},
    'TH5606': <String, String>{'name': 'ปง', 'alpha': 'ป'}
  },
  'TH57': <String, Map<String, String>>{
    'TH5703': <String, String>{'name': 'เชียงของ', 'alpha': 'เ'},
    'TH5708': <String, String>{'name': 'เชียงแสน', 'alpha': 'เ'},
    'TH5718': <String, String>{'name': 'ดอยหลวง', 'alpha': 'ด'},
    'TH5714': <String, String>{'name': 'ขุนตาล', 'alpha': 'ขุ'},
    'TH5707': <String, String>{'name': 'แม่จัน', 'alpha': 'แ'},
    'TH5715': <String, String>{'name': 'แม่ฟ้าหลวง', 'alpha': 'แ'},
    'TH5716': <String, String>{'name': 'แม่ลาว', 'alpha': 'แ'},
    'TH5709': <String, String>{'name': 'แม่สาย', 'alpha': 'แ'},
    'TH5710': <String, String>{'name': 'แม่สรวย', 'alpha': 'แ'},
    'TH5701': <String, String>{'name': 'เมืองเชียงราย', 'alpha': 'เ'},
    'TH5706': <String, String>{'name': 'ป่าแดด', 'alpha': 'ป่'},
    'TH5705': <String, String>{'name': 'พาน', 'alpha': 'พ'},
    'TH5712': <String, String>{'name': 'พญาเม็งราย', 'alpha': 'พ'},
    'TH5704': <String, String>{'name': 'เทิง', 'alpha': 'เ'},
    'TH5702': <String, String>{'name': 'เวียงชัย', 'alpha': 'เ'},
    'TH5717': <String, String>{'name': 'เวียงเชียงรุ้ง', 'alpha': 'เ'},
    'TH5713': <String, String>{'name': 'เวียงแก่น', 'alpha': 'เ'},
    'TH5711': <String, String>{'name': 'เวียงป่าเป้า', 'alpha': 'เ'}
  },
  'TH58': <String, Map<String, String>>{
    'TH5802': <String, String>{'name': 'ขุนยวม', 'alpha': 'ขุ'},
    'TH5805': <String, String>{'name': 'แม่ลาน้อย', 'alpha': 'แ'},
    'TH5804': <String, String>{'name': 'แม่สะเรียง', 'alpha': 'แ'},
    'TH5801': <String, String>{'name': 'เมืองแม่ฮ่องสอน', 'alpha': 'เ'},
    'TH5803': <String, String>{'name': 'ปาย', 'alpha': 'ป'},
    'TH5807': <String, String>{'name': 'ปางมะผ้า', 'alpha': 'ป'},
    'TH5806': <String, String>{'name': 'สบเมย', 'alpha': 'ส'}
  },
  'TH60': <String, Map<String, String>>{
    'TH6005': <String, String>{'name': 'บรรพตพิสัย', 'alpha': 'บ'},
    'TH6003': <String, String>{'name': 'ชุมแสง', 'alpha': 'ชุ'},
    'TH6015': <String, String>{'name': 'ชุมตาบง', 'alpha': 'ชุ'},
    'TH6006': <String, String>{'name': 'เก้าเลี้ยว', 'alpha': 'เ'},
    'TH6002': <String, String>{'name': 'โกรกพระ', 'alpha': 'โ'},
    'TH6011': <String, String>{'name': 'ลาดยาว', 'alpha': 'ล'},
    'TH6014': <String, String>{'name': 'แม่เปิน', 'alpha': 'แ'},
    'TH6013': <String, String>{'name': 'แม่วงก์', 'alpha': 'แ'},
    'TH6001': <String, String>{'name': 'เมืองนครสวรรค์', 'alpha': 'เ'},
    'TH6004': <String, String>{'name': 'หนองบัว', 'alpha': 'ห'},
    'TH6009': <String, String>{'name': 'ไพศาลี', 'alpha': 'ไ'},
    'TH6010': <String, String>{'name': 'พยุหะคีรี', 'alpha': 'พ'},
    'TH6012': <String, String>{'name': 'ตากฟ้า', 'alpha': 'ต'},
    'TH6007': <String, String>{'name': 'ตาคลี', 'alpha': 'ต'},
    'TH6008': <String, String>{'name': 'ท่าตะโก', 'alpha': 'ท่'}
  },
  'TH61': <String, Map<String, String>>{
    'TH6106': <String, String>{'name': 'บ้านไร่', 'alpha': 'บ้'},
    'TH6108': <String, String>{'name': 'ห้วยคต', 'alpha': 'ห้'},
    'TH6107': <String, String>{'name': 'ลานสัก', 'alpha': 'ล'},
    'TH6101': <String, String>{'name': 'เมืองอุทัยธานี', 'alpha': 'เ'},
    'TH6104': <String, String>{'name': 'หนองฉาง', 'alpha': 'ห'},
    'TH6105': <String, String>{'name': 'หนองขาหย่าง', 'alpha': 'ห'},
    'TH6103': <String, String>{'name': 'สว่างอารมณ์', 'alpha': 'ส'},
    'TH6102': <String, String>{'name': 'ทัพทัน', 'alpha': 'ทั'}
  },
  'TH62': <String, Map<String, String>>{
    'TH6210': <String, String>{'name': 'บึงสามัคคี', 'alpha': 'บึ'},
    'TH6204': <String, String>{'name': 'ขาณุวรลักษบุรี', 'alpha': 'ข'},
    'TH6205': <String, String>{'name': 'คลองขลุง', 'alpha': 'ค'},
    'TH6203': <String, String>{'name': 'คลองลาน', 'alpha': 'ค'},
    'TH6211': <String, String>{'name': 'โกสัมพีนคร', 'alpha': 'โ'},
    'TH6207': <String, String>{'name': 'ลานกระบือ', 'alpha': 'ล'},
    'TH6201': <String, String>{'name': 'เมืองกำแพงเพชร', 'alpha': 'เ'},
    'TH6209': <String, String>{'name': 'ปางศิลาทอง', 'alpha': 'ป'},
    'TH6206': <String, String>{'name': 'พรานกระต่าย', 'alpha': 'พ'},
    'TH6202': <String, String>{'name': 'ไทรงาม', 'alpha': 'ไ'},
    'TH6208': <String, String>{'name': 'ทรายทองวัฒนา', 'alpha': 'ท'}
  },
  'TH63': <String, Map<String, String>>{
    'TH6302': <String, String>{'name': 'บ้านตาก', 'alpha': 'บ้'},
    'TH6304': <String, String>{'name': 'แม่ระมาด', 'alpha': 'แ'},
    'TH6306': <String, String>{'name': 'แม่สอด', 'alpha': 'แ'},
    'TH6301': <String, String>{'name': 'เมืองตาก', 'alpha': 'เ'},
    'TH6307': <String, String>{'name': 'พบพระ', 'alpha': 'พ'},
    'TH6303': <String, String>{'name': 'สามเงา', 'alpha': 'ส'},
    'TH6305': <String, String>{'name': 'ท่าสองยาง', 'alpha': 'ท่'},
    'TH6308': <String, String>{'name': 'อุ้มผาง', 'alpha': 'อุ้'},
    'TH6309': <String, String>{'name': 'วังเจ้า', 'alpha': 'วั'}
  },
  'TH64': <String, Map<String, String>>{
    'TH6402': <String, String>{'name': 'บ้านด่านลานหอย', 'alpha': 'บ้'},
    'TH6403': <String, String>{'name': 'คีรีมาศ', 'alpha': 'คี'},
    'TH6404': <String, String>{'name': 'กงไกรลาศ', 'alpha': 'ก'},
    'TH6401': <String, String>{'name': 'เมืองสุโขทัย', 'alpha': 'เ'},
    'TH6407': <String, String>{'name': 'สวรรคโลก', 'alpha': 'ส'},
    'TH6408': <String, String>{'name': 'ศรีนคร', 'alpha': 'ศ'},
    'TH6406': <String, String>{'name': 'ศรีสำโรง', 'alpha': 'ศ'},
    'TH6405': <String, String>{'name': 'ศรีสัชนาลัย', 'alpha': 'ศ'},
    'TH6409': <String, String>{'name': 'ทุ่งเสลี่ยม', 'alpha': 'ทุ่'}
  },
  'TH65': <String, Map<String, String>>{
    'TH6505': <String, String>{'name': 'บางกระทุ่ม', 'alpha': 'บ'},
    'TH6504': <String, String>{'name': 'บางระกำ', 'alpha': 'บ'},
    'TH6503': <String, String>{'name': 'ชาติตระการ', 'alpha': 'ช'},
    'TH6501': <String, String>{'name': 'เมืองพิษณุโลก', 'alpha': 'เ'},
    'TH6502': <String, String>{'name': 'นครไทย', 'alpha': 'น'},
    'TH6509': <String, String>{'name': 'เนินมะปราง', 'alpha': 'เ'},
    'TH6506': <String, String>{'name': 'พรหมพิราม', 'alpha': 'พ'},
    'TH6508': <String, String>{'name': 'วังทอง', 'alpha': 'วั'},
    'TH6507': <String, String>{'name': 'วัดโบสถ์', 'alpha': 'วั'}
  },
  'TH66': <String, Map<String, String>>{
    'TH6605': <String, String>{'name': 'บางมูลนาก', 'alpha': 'บ'},
    'TH6610': <String, String>{'name': 'บึงนาราง', 'alpha': 'บึ'},
    'TH6611': <String, String>{'name': 'ดงเจริญ', 'alpha': 'ด'},
    'TH6601': <String, String>{'name': 'เมืองพิจิตร', 'alpha': 'เ'},
    'TH6603': <String, String>{'name': 'โพธิ์ประทับช้าง', 'alpha': 'โ'},
    'TH6606': <String, String>{'name': 'โพทะเล', 'alpha': 'โ'},
    'TH6609': <String, String>{'name': 'สากเหล็ก', 'alpha': 'ส'},
    'TH6607': <String, String>{'name': 'สามง่าม', 'alpha': 'ส'},
    'TH6608': <String, String>{'name': 'ทับคล้อ', 'alpha': 'ทั'},
    'TH6604': <String, String>{'name': 'ตะพานหิน', 'alpha': 'ต'},
    'TH6612': <String, String>{'name': 'วชิรบารมี', 'alpha': 'ว'},
    'TH6602': <String, String>{'name': 'วังทรายพูน', 'alpha': 'วั'}
  },
  'TH67': <String, Map<String, String>>{
    'TH6708': <String, String>{'name': 'บึงสามพัน', 'alpha': 'บึ'},
    'TH6702': <String, String>{'name': 'ชนแดน', 'alpha': 'ช'},
    'TH6711': <String, String>{'name': 'เขาค้อ', 'alpha': 'เ'},
    'TH6704': <String, String>{'name': 'หล่มเก่า', 'alpha': 'ห'},
    'TH6703': <String, String>{'name': 'หล่มสัก', 'alpha': 'ห'},
    'TH6701': <String, String>{'name': 'เมืองเพชรบูรณ์', 'alpha': 'เ'},
    'TH6709': <String, String>{'name': 'น้ำหนาว', 'alpha': 'น้ำ'},
    'TH6707': <String, String>{'name': 'หนองไผ่', 'alpha': 'ห'},
    'TH6706': <String, String>{'name': 'ศรีเทพ', 'alpha': 'ศ'},
    'TH6710': <String, String>{'name': 'วังโป่ง', 'alpha': 'วั'},
    'TH6705': <String, String>{'name': 'วิเชียรบุรี', 'alpha': 'วิ'}
  },
  'TH70': <String, Map<String, String>>{
    'TH7010': <String, String>{'name': 'บ้านคา', 'alpha': 'บ้'},
    'TH7005': <String, String>{'name': 'บ้านโป่ง', 'alpha': 'บ้'},
    'TH7006': <String, String>{'name': 'บางแพ', 'alpha': 'บ'},
    'TH7002': <String, String>{'name': 'จอมบึง', 'alpha': 'จ'},
    'TH7004': <String, String>{'name': 'ดำเนินสะดวก', 'alpha': 'ดำ'},
    'TH7001': <String, String>{'name': 'เมืองราชบุรี', 'alpha': 'เ'},
    'TH7008': <String, String>{'name': 'ปากท่อ', 'alpha': 'ป'},
    'TH7007': <String, String>{'name': 'โพธาราม', 'alpha': 'โ'},
    'TH7003': <String, String>{'name': 'สวนผึ้ง', 'alpha': 'ส'},
    'TH7009': <String, String>{'name': 'วัดเพลง', 'alpha': 'วั'}
  },
  'TH71': <String, Map<String, String>>{
    'TH7103': <String, String>{'name': 'บ่อพลอย', 'alpha': 'บ่'},
    'TH7111': <String, String>{'name': 'ด่านมะขามเตี้ย', 'alpha': 'ด่'},
    'TH7113': <String, String>{'name': 'ห้วยกระเจา', 'alpha': 'ห้'},
    'TH7110': <String, String>{'name': 'เลาขวัญ', 'alpha': 'เ'},
    'TH7101': <String, String>{'name': 'เมืองกาญจนบุรี', 'alpha': 'เ'},
    'TH7112': <String, String>{'name': 'หนองปรือ', 'alpha': 'ห'},
    'TH7109': <String, String>{'name': 'พนมทวน', 'alpha': 'พ'},
    'TH7102': <String, String>{'name': 'ไทรโยค', 'alpha': 'ไ'},
    'TH7108': <String, String>{'name': 'สังขละบุรี', 'alpha': 'สั'},
    'TH7104': <String, String>{'name': 'ศรีสวัสดิ์', 'alpha': 'ศ'},
    'TH7105': <String, String>{'name': 'ท่ามะกา', 'alpha': 'ท่'},
    'TH7106': <String, String>{'name': 'ท่าม่วง', 'alpha': 'ท่'},
    'TH7107': <String, String>{'name': 'ทองผาภูมิ', 'alpha': 'ท'}
  },
  'TH72': <String, Map<String, String>>{
    'TH7204': <String, String>{'name': 'บางปลาม้า', 'alpha': 'บ'},
    'TH7203': <String, String>{'name': 'ด่านช้าง', 'alpha': 'ด่'},
    'TH7202': <String, String>{'name': 'เดิมบางนางบวช', 'alpha': 'เ'},
    'TH7206': <String, String>{'name': 'ดอนเจดีย์', 'alpha': 'ด'},
    'TH7201': <String, String>{'name': 'เมืองสุพรรณบุรี', 'alpha': 'เ'},
    'TH7210': <String, String>{'name': 'หนองหญ้าไซ', 'alpha': 'ห'},
    'TH7208': <String, String>{'name': 'สามชุก', 'alpha': 'ส'},
    'TH7205': <String, String>{'name': 'ศรีประจันต์', 'alpha': 'ศ'},
    'TH7207': <String, String>{'name': 'สองพี่น้อง', 'alpha': 'ส'},
    'TH7209': <String, String>{'name': 'อู่ทอง', 'alpha': 'อู่'}
  },
  'TH73': <String, Map<String, String>>{
    'TH7305': <String, String>{'name': 'บางเลน', 'alpha': 'บ'},
    'TH7304': <String, String>{'name': 'ดอนตูม', 'alpha': 'ด'},
    'TH7302': <String, String>{'name': 'กำแพงแสน', 'alpha': 'กำ'},
    'TH7301': <String, String>{'name': 'เมืองนครปฐม', 'alpha': 'เ'},
    'TH7303': <String, String>{'name': 'นครชัยศรี', 'alpha': 'น'},
    'TH7307': <String, String>{'name': 'พุทธมณฑล', 'alpha': 'พุ'},
    'TH7306': <String, String>{'name': 'สามพราน', 'alpha': 'ส'}
  },
  'TH74': <String, Map<String, String>>{
    'TH7403': <String, String>{'name': 'บ้านแพ้ว', 'alpha': 'บ้'},
    'TH7402': <String, String>{'name': 'กระทุ่มแบน', 'alpha': 'ก'},
    'TH7401': <String, String>{'name': 'เมืองสมุทรสาคร', 'alpha': 'เ'}
  },
  'TH75': <String, Map<String, String>>{
    'TH7503': <String, String>{'name': 'อัมพวา', 'alpha': 'อั'},
    'TH7502': <String, String>{'name': 'บางคนที', 'alpha': 'บ'},
    'TH7501': <String, String>{'name': 'เมืองสมุทรสงคราม', 'alpha': 'เ'}
  },
  'TH76': <String, Map<String, String>>{
    'TH7607': <String, String>{'name': 'บ้านแหลม', 'alpha': 'บ้'},
    'TH7606': <String, String>{'name': 'บ้านลาด', 'alpha': 'บ้'},
    'TH7604': <String, String>{'name': 'ชะอำ', 'alpha': 'ช'},
    'TH7608': <String, String>{'name': 'แก่งกระจาน', 'alpha': 'แ'},
    'TH7602': <String, String>{'name': 'เขาย้อย', 'alpha': 'เ'},
    'TH7601': <String, String>{'name': 'เมืองเพชรบุรี', 'alpha': 'เ'},
    'TH7603': <String, String>{'name': 'หนองหญ้าปล้อง', 'alpha': 'ห'},
    'TH7605': <String, String>{'name': 'ท่ายาง', 'alpha': 'ท่'}
  },
  'TH77': <String, Map<String, String>>{
    'TH7704': <String, String>{'name': 'บางสะพาน', 'alpha': 'บ'},
    'TH7705': <String, String>{'name': 'บางสะพานน้อย', 'alpha': 'บ'},
    'TH7707': <String, String>{'name': 'หัวหิน', 'alpha': 'หั'},
    'TH7702': <String, String>{'name': 'กุยบุรี', 'alpha': 'กุ'},
    'TH7701': <String, String>{'name': 'เมืองประจวบคีรีข', 'alpha': 'เ'},
    'TH7706': <String, String>{'name': 'ปราณบุรี', 'alpha': 'ป'},
    'TH7708': <String, String>{'name': 'สามร้อยยอด', 'alpha': 'ส'},
    'TH7703': <String, String>{'name': 'ทับสะแก', 'alpha': 'ทั'}
  },
  'TH80': <String, Map<String, String>>{
    'TH8017': <String, String>{'name': 'บางขัน', 'alpha': 'บ'},
    'TH8007': <String, String>{'name': 'ชะอวด', 'alpha': 'ช'},
    'TH8023': <String, String>{'name': 'เฉลิมพระเกียรติ', 'alpha': 'เ'},
    'TH8022': <String, String>{'name': 'ช้างกลาง', 'alpha': 'ช้'},
    'TH8004': <String, String>{'name': 'ฉวาง', 'alpha': 'ฉ'},
    'TH8006': <String, String>{'name': 'เชียรใหญ่', 'alpha': 'เ'},
    'TH8019': <String, String>{'name': 'จุฬาภรณ์', 'alpha': 'จุ'},
    'TH8016': <String, String>{'name': 'หัวไทร', 'alpha': 'หั'},
    'TH8015': <String, String>{'name': 'ขนอม', 'alpha': 'ข'},
    'TH8003': <String, String>{'name': 'ลานสกา', 'alpha': 'ล'},
    'TH8001': <String, String>{'name': 'เมืองนครศรีธรรมร', 'alpha': 'เ'},
    'TH8010': <String, String>{'name': 'นาบอน', 'alpha': 'น'},
    'TH8021': <String, String>{'name': 'นบพิตำ', 'alpha': 'น'},
    'TH8012': <String, String>{'name': 'ปากพนัง', 'alpha': 'ป'},
    'TH8005': <String, String>{'name': 'พิปูน', 'alpha': 'พิ'},
    'TH8020': <String, String>{'name': 'พระพรหม', 'alpha': 'พ'},
    'TH8002': <String, String>{'name': 'พรหมคีรี', 'alpha': 'พ'},
    'TH8013': <String, String>{'name': 'ร่อนพิบูลย์', 'alpha': 'ร่'},
    'TH8014': <String, String>{'name': 'สิชล', 'alpha': 'สิ'},
    'TH8008': <String, String>{'name': 'ท่าศาลา', 'alpha': 'ท่'},
    'TH8018': <String, String>{'name': 'ถ้ำพรรณรา', 'alpha': 'ถ้ำ'},
    'TH8009': <String, String>{'name': 'ทุ่งสง', 'alpha': 'ทุ่'},
    'TH8011': <String, String>{'name': 'ทุ่งใหญ่', 'alpha': 'ทุ่'}
  },
  'TH81': <String, Map<String, String>>{
    'TH8105': <String, String>{'name': 'อ่าวลึก', 'alpha': 'อ่'},
    'TH8102': <String, String>{'name': 'เขาพนม', 'alpha': 'เ'},
    'TH8104': <String, String>{'name': 'คลองท่อม', 'alpha': 'ค'},
    'TH8103': <String, String>{'name': 'เกาะลันตา', 'alpha': 'เ'},
    'TH8107': <String, String>{'name': 'ลำทับ', 'alpha': 'ลำ'},
    'TH8101': <String, String>{'name': 'เมืองกระบี่', 'alpha': 'เ'},
    'TH8108': <String, String>{'name': 'เหนือคลอง', 'alpha': 'เ'},
    'TH8106': <String, String>{'name': 'ปลายพระยา', 'alpha': 'ป'}
  },
  'TH82': <String, Map<String, String>>{
    'TH8203': <String, String>{'name': 'กะปง', 'alpha': 'ก'},
    'TH8206': <String, String>{'name': 'คุระบุรี', 'alpha': 'คุ'},
    'TH8202': <String, String>{'name': 'เกาะยาว', 'alpha': 'เ'},
    'TH8201': <String, String>{'name': 'เมืองพังงา', 'alpha': 'เ'},
    'TH8205': <String, String>{'name': 'ตะกั่วป่า', 'alpha': 'ต'},
    'TH8204': <String, String>{'name': 'ตะกั่วทุ่ง', 'alpha': 'ต'},
    'TH8208': <String, String>{'name': 'ท้ายเหมือง', 'alpha': 'ท้'},
    'TH8207': <String, String>{'name': 'ทับปุด', 'alpha': 'ทั'}
  },
  'TH83': <String, Map<String, String>>{
    'TH8302': <String, String>{'name': 'กะทู้', 'alpha': 'ก'},
    'TH8301': <String, String>{'name': 'เมืองภูเก็ต', 'alpha': 'เ'},
    'TH8303': <String, String>{'name': 'ถลาง', 'alpha': 'ถ'}
  },
  'TH84': <String, Map<String, String>>{
    'TH8413': <String, String>{'name': 'บ้านนาเดิม', 'alpha': 'บ้'},
    'TH8412': <String, String>{'name': 'บ้านนาสาร', 'alpha': 'บ้'},
    'TH8409': <String, String>{'name': 'บ้านตาขุน', 'alpha': 'บ้'},
    'TH8418': <String, String>{'name': 'ชัยบุรี', 'alpha': 'ชั'},
    'TH8406': <String, String>{'name': 'ไชยา', 'alpha': 'ไ'},
    'TH8403': <String, String>{'name': 'ดอนสัก', 'alpha': 'ด'},
    'TH8402': <String, String>{'name': 'กาญจนดิษฐ์', 'alpha': 'ก'},
    'TH8414': <String, String>{'name': 'เคียนซา', 'alpha': 'เ'},
    'TH8408': <String, String>{'name': 'คีรีรัฐนิคม', 'alpha': 'คี'},
    'TH8405': <String, String>{'name': 'เกาะพะงัน', 'alpha': 'เ'},
    'TH8404': <String, String>{'name': 'เกาะสมุย', 'alpha': 'เ'},
    'TH8401': <String, String>{'name': 'เมืองสุราษฎร์ธาน', 'alpha': 'เ'},
    'TH8410': <String, String>{'name': 'พนม', 'alpha': 'พ'},
    'TH8416': <String, String>{'name': 'พระแสง', 'alpha': 'พ'},
    'TH8417': <String, String>{'name': 'พุนพิน', 'alpha': 'พุ'},
    'TH8407': <String, String>{'name': 'ท่าชนะ', 'alpha': 'ท่'},
    'TH8411': <String, String>{'name': 'ท่าฉาง', 'alpha': 'ท่'},
    'TH8419': <String, String>{'name': 'วิภาวดี', 'alpha': 'วิ'},
    'TH8415': <String, String>{'name': 'เวียงสระ', 'alpha': 'เ'}
  },
  'TH85': <String, Map<String, String>>{
    'TH8503': <String, String>{'name': 'กะเปอร์', 'alpha': 'ก'},
    'TH8504': <String, String>{'name': 'กระบุรี', 'alpha': 'ก'},
    'TH8502': <String, String>{'name': 'ละอุ่น', 'alpha': 'ล'},
    'TH8501': <String, String>{'name': 'เมืองระนอง', 'alpha': 'เ'},
    'TH8505': <String, String>{'name': 'สุขสำราญ', 'alpha': 'สุ'}
  },
  'TH86': <String, Map<String, String>>{
    'TH8605': <String, String>{'name': 'ละแม', 'alpha': 'ล'},
    'TH8604': <String, String>{'name': 'หลังสวน', 'alpha': 'ห'},
    'TH8601': <String, String>{'name': 'เมืองชุมพร', 'alpha': 'เ'},
    'TH8603': <String, String>{'name': 'ปะทิว', 'alpha': 'ป'},
    'TH8606': <String, String>{'name': 'พะโต๊ะ', 'alpha': 'พ'},
    'TH8607': <String, String>{'name': 'สวี', 'alpha': 'ส'},
    'TH8602': <String, String>{'name': 'ท่าแซะ', 'alpha': 'ท่'},
    'TH8608': <String, String>{'name': 'ทุ่งตะโก', 'alpha': 'ทุ่'}
  },
  'TH90': <String, Map<String, String>>{
    'TH9014': <String, String>{'name': 'บางกล่ำ', 'alpha': 'บ'},
    'TH9003': <String, String>{'name': 'จะนะ', 'alpha': 'จ'},
    'TH9011': <String, String>{'name': 'หาดใหญ่', 'alpha': 'ห'},
    'TH9016': <String, String>{'name': 'คลองหอยโข่ง', 'alpha': 'ค'},
    'TH9013': <String, String>{'name': 'ควนเนียง', 'alpha': 'ค'},
    'TH9008': <String, String>{'name': 'กระแสสินธุ์', 'alpha': 'ก'},
    'TH9001': <String, String>{'name': 'เมืองสงขลา', 'alpha': 'เ'},
    'TH9012': <String, String>{'name': 'นาหม่อม', 'alpha': 'น'},
    'TH9004': <String, String>{'name': 'นาทวี', 'alpha': 'น'},
    'TH9007': <String, String>{'name': 'ระโนด', 'alpha': 'ร'},
    'TH9009': <String, String>{'name': 'รัตภูมิ', 'alpha': 'รั'},
    'TH9006': <String, String>{'name': 'สะบ้าย้อย', 'alpha': 'ส'},
    'TH9010': <String, String>{'name': 'สะเดา', 'alpha': 'ส'},
    'TH9002': <String, String>{'name': 'สทิงพระ', 'alpha': 'ส'},
    'TH9015': <String, String>{'name': 'สิงหนคร', 'alpha': 'สิ'},
    'TH9005': <String, String>{'name': 'เทพา', 'alpha': 'เ'}
  },
  'TH91': <String, Map<String, String>>{
    'TH9102': <String, String>{'name': 'ควนโดน', 'alpha': 'ค'},
    'TH9103': <String, String>{'name': 'ควนกาหลง', 'alpha': 'ค'},
    'TH9105': <String, String>{'name': 'ละงู', 'alpha': 'ล'},
    'TH9107': <String, String>{'name': 'มะนัง', 'alpha': 'ม'},
    'TH9101': <String, String>{'name': 'เมืองสตูล', 'alpha': 'เ'},
    'TH9104': <String, String>{'name': 'ท่าแพ', 'alpha': 'ท่'},
    'TH9106': <String, String>{'name': 'ทุ่งหว้า', 'alpha': 'ทุ่'}
  },
  'TH92': <String, Map<String, String>>{
    'TH9210': <String, String>{'name': 'หาดสำราญ', 'alpha': 'ห'},
    'TH9206': <String, String>{'name': 'ห้วยยอด', 'alpha': 'ห้'},
    'TH9202': <String, String>{'name': 'กันตัง', 'alpha': 'กั'},
    'TH9201': <String, String>{'name': 'เมืองตรัง', 'alpha': 'เ'},
    'TH9208': <String, String>{'name': 'นาโยง', 'alpha': 'น'},
    'TH9204': <String, String>{'name': 'ปะเหลียน', 'alpha': 'ป'},
    'TH9209': <String, String>{'name': 'รัษฎา', 'alpha': 'รั'},
    'TH9205': <String, String>{'name': 'สิเกา', 'alpha': 'สิ'},
    'TH9207': <String, String>{'name': 'วังวิเศษ', 'alpha': 'วั'},
    'TH9203': <String, String>{'name': 'ย่านตาขาว', 'alpha': 'ย่'}
  },
  'TH93': <String, Map<String, String>>{
    'TH9309': <String, String>{'name': 'บางแก้ว', 'alpha': 'บ'},
    'TH9303': <String, String>{'name': 'เขาชัยสน', 'alpha': 'เ'},
    'TH9305': <String, String>{'name': 'ควนขนุน', 'alpha': 'ค'},
    'TH9302': <String, String>{'name': 'กงหรา', 'alpha': 'ก'},
    'TH9301': <String, String>{'name': 'เมืองพัทลุง', 'alpha': 'เ'},
    'TH9308': <String, String>{'name': 'ป่าบอน', 'alpha': 'ป่'},
    'TH9310': <String, String>{'name': 'ป่าพะยอม', 'alpha': 'ป่'},
    'TH9306': <String, String>{'name': 'ปากพะยูน', 'alpha': 'ป'},
    'TH9307': <String, String>{'name': 'ศรีบรรพต', 'alpha': 'ศ'},
    'TH9311': <String, String>{'name': 'ศรีนครินทร์', 'alpha': 'ศ'},
    'TH9304': <String, String>{'name': 'ตะโหมด', 'alpha': 'ต'}
  },
  'TH94': <String, Map<String, String>>{
    'TH9411': <String, String>{'name': 'กะพ้อ', 'alpha': 'ก'},
    'TH9402': <String, String>{'name': 'โคกโพธิ์', 'alpha': 'โ'},
    'TH9412': <String, String>{'name': 'แม่ลาน', 'alpha': 'แ'},
    'TH9408': <String, String>{'name': 'ไม้แก่น', 'alpha': 'ไ'},
    'TH9405': <String, String>{'name': 'มายอ', 'alpha': 'ม'},
    'TH9401': <String, String>{'name': 'เมืองปัตตานี', 'alpha': 'เ'},
    'TH9403': <String, String>{'name': 'หนองจิก', 'alpha': 'ห'},
    'TH9404': <String, String>{'name': 'ปะนาเระ', 'alpha': 'ป'},
    'TH9407': <String, String>{'name': 'สายบุรี', 'alpha': 'ส'},
    'TH9406': <String, String>{'name': 'ทุ่งยางแดง', 'alpha': 'ทุ่'},
    'TH9410': <String, String>{'name': 'ยะรัง', 'alpha': 'ย'},
    'TH9409': <String, String>{'name': 'ยะหริ่ง', 'alpha': 'ย'}
  },
  'TH95': <String, Map<String, String>>{
    'TH9503': <String, String>{'name': 'บันนังสตา', 'alpha': 'บั'},
    'TH9502': <String, String>{'name': 'เบตง', 'alpha': 'เ'},
    'TH9507': <String, String>{'name': 'กาบัง', 'alpha': 'ก'},
    'TH9508': <String, String>{'name': 'กรงปินัง', 'alpha': 'ก'},
    'TH9501': <String, String>{'name': 'เมืองยะลา', 'alpha': 'เ'},
    'TH9506': <String, String>{'name': 'รามัน', 'alpha': 'ร'},
    'TH9504': <String, String>{'name': 'ธารโต', 'alpha': 'ธ'},
    'TH9505': <String, String>{'name': 'ยะหา', 'alpha': 'ย'}
  },
  'TH96': <String, Map<String, String>>{
    'TH9603': <String, String>{'name': 'บาเจาะ', 'alpha': 'บ'},
    'TH9612': <String, String>{'name': 'จะแนะ', 'alpha': 'จ'},
    'TH9613': <String, String>{'name': 'เจาะไอร้อง', 'alpha': 'เ'},
    'TH9601': <String, String>{'name': 'เมืองนราธิวาส', 'alpha': 'เ'},
    'TH9605': <String, String>{'name': 'ระแงะ', 'alpha': 'ร'},
    'TH9606': <String, String>{'name': 'รือเสาะ', 'alpha': 'รื'},
    'TH9607': <String, String>{'name': 'ศรีสาคร', 'alpha': 'ศ'},
    'TH9610': <String, String>{'name': 'สุไหงโก-ลก', 'alpha': 'สุ'},
    'TH9611': <String, String>{'name': 'สุไหงปาดี', 'alpha': 'สุ'},
    'TH9609': <String, String>{'name': 'สุคิริน', 'alpha': 'สุ'},
    'TH9602': <String, String>{'name': 'ตากใบ', 'alpha': 'ต'},
    'TH9608': <String, String>{'name': 'แว้ง', 'alpha': 'แ'},
    'TH9604': <String, String>{'name': 'ยี่งอ', 'alpha': 'ยี่'}
  }
};
